### ISSUE TITLE
Improve timeline notes to reference note author/editor

### ISSUE THREAD

**Issue by CLBarajas** [josephwegner/carrick-issues-tracker#11]
Related to #5, maybe, but it would be nice to know who adds comments. (Particularly, if the bot is commenting to add another reference.)

**Comment by josephwegner** [comment]
Can do that - I think I originally left it out to avoid text wrapping, but I'll add it in and see how it looks.

Also seems like bot comments probably should not be listed there. I'll filter them out.

**Comment by josephwegner** [comment]
Shipped.

**Comment by josephwegner** [comment]
FWIW, I left in the bot comments for the moment. Haven't decided definitively if it's better to remove them. Open to feedback there.
