### ISSUE TITLE
Multiple notifications are posted into the same Github Issue when the issue is linked

### ISSUE THREAD

**Issue by josephwegner** [josephwegner/carrick-issues-tracker#13]

**Comment by josephwegner** [comment]
@CLBarajas I'm not able to repro this. To clarify, you're seeing multiple comments posted on the same issue by Carrick?

**Comment by CLBarajas** [comment]
Maybe I'm mis-remembering. I can re-check our items that have multiple links and see if there's more than one bot comment.

**Comment by CLBarajas** [comment]
OK, tested this today and it's no longer happening (if it ever happened). Guess that was a false alarm.

**Comment by josephwegner** [comment]
OK, closing it out. If it comes back up again, feel free to comment+reopen.
