### ISSUE TITLE
Multiple links can be created by opening new tabs from a single conversation, but not seen in sidebar

### ISSUE THREAD

**Issue by CLBarajas** [josephwegner/carrick-issues-tracker#7]
**Bug description:**
A Help Scout conversation can link to multiple issues by opening links in new tabs, but only the first is visible.

**Steps to reproduce:**
Browser tested: Safari 14 (macOS 10.15)

1. Open a conversation
2. Use the "Link to Existing Issue" button to open new tabs
3. Link multiple new issues in those separate tabs
4. Refresh the original page

**Expected behavior:**
Multiple links listed in sidebar.

**Observed issue:**
First linked item is what's seen.

**Additional data:**
The conversations are linked within Carrick Issues, and as seen from comments in the respective issues.

**Comment by josephwegner** [comment]
Thanks!

This will be fixed shortly, when multiple linked issues launches. I finished research on that this morning, am starting dev tomorrow.

**Comment by josephwegner** [comment]
Here's a longer-form view. 

![image](https://user-images.githubusercontent.com/657707/96116259-cf996600-0ead-11eb-8e80-fa30228354bb.png)


This is ready to ship, but I'm going to let it sit for a day or two to make sure I/we feel confident in the design.

**Comment by josephwegner** [comment]
Shipped.
