### ISSUE TITLE
Carrick doesn't track/update transferred issues

### ISSUE THREAD

**Issue by CLBarajas** [josephwegner/carrick-issues-tracker#8]
**Bug description:**
If you transfer an issue between repositories in GitHub, Carrick fails to track it

**Steps to reproduce:**
1. Link an existing GitHub issue using Carrick sidebar app in Help Scout
2. View issue in GitHub
3. Transfer to another repository

**Expected behavior:**
Issue info updated in sidebar app when refreshing conversation.

**Observed issue:**
Internal Server Error

**Additional data:**
In my setup, both repositories' issues have allowed access to Carrick.

**Comment by CLBarajas** [comment]
For more context here, our team uses two separate repositories: a `support` repo that tracks general issues that need further verification or testing, and a `main` repo that does all of our development planning. When a `support` issue is verified to be a bug report or feature request, it gets transferred into the `main` repo and prioritized along with other work - and that breaks the Carrick Issues connection between GitHub and Help Scout.

**Comment by josephwegner** [comment]
This should be done, but waiting on #5 and multiple-linked-issues to ship first.

**Comment by josephwegner** [comment]
Shipped.
